spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vueblog2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#mybatis配置
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mybatis/*.xml

server:
  port: 8080
  compression:
    enabled: true
